### ISSUE TITLE
Cannot install zookeeper

### ISSUE THREAD

**Issue by Reeebuuk** [yfinkelstein/node-zookeeper#113]
Hi guys,

win 7 64bit, node 0.12.5.

C:\Working\Apps\kibana-4.1.1-windows>npm install zookeeper
-
> zookeeper@3.4.6 install C:\Working\Apps\kibana-4.1.1-windows\node_modules\zookeeper
> node-gyp rebuild

C:\Working\Apps\kibana-4.1.1-windows\node_modules\zookeeper>if not defined npm_config_node_gyp (node "c:\Working\Apps\NodeJS\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): warning MSB8017: A circular dependency has been detected w
hile executing custom build commands for item ".". This may cause incremental build to work incorrectly. [C:\Working\Apps\kibana-4.1.1-windows\node_m
odules\zookeeper\build\libzk.vcxproj]
  build_zk_client_lib
  'sh' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Working\A
pps\kibana-4.1.1-windows\node_modules\zookeeper\build\libzk.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Working\Apps\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Working\\Apps\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Working\Apps\kibana-4.1.1-windows\node_modules\zookeeper
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Working\\Apps\\NodeJS\\\\node.exe" "c:\\Working\\Apps\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "zookeeper"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! zookeeper@3.4.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zookeeper@3.4.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zookeeper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zookeeper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Working\Apps\kibana-4.1.1-windows\npm-debug.log

**Comment by mdlavin** [comment]
Failure to install on windows is currently being tracked in #78
