### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by V1cHu** [yfinkelstein/node-zookeeper#115]
It leaves this message : 

	npm WARN package.json zookeeper@3.4.6-7 No license field.                                                                                                               

	> zookeeper@3.4.6-7 install E:\zookeeper\zeek\node_modules\node-zookeeper                                                                                               
	> node-gyp rebuild                                                                                                                                                      

	E:\zookeeper\zeek\node_modules\node-zookeeper>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
	de-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )                                                                                                                
	Traceback (most recent call last):                                                                                                                                      
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>                                                           
		sys.exit(gyp.script_main())                                                                                                                                         
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 533, in script_main                                             
		return main(sys.argv[1:])                                                                                                                                           
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 526, in main                                                    
		return gyp_main(args)                                                                                                                                               
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 511, in gyp_main                                                
		generator.GenerateOutput(flat_list, targets, data, params)                                                                                                          
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1985, in GenerateOutput                                   
		generator_flags))                                                                                                                                                   
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 924, in _GenerateProject                                  
		return _GenerateMSVSProject(project, options, version, generator_flags)                                                                                             
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1025, in _GenerateMSVSProject                             
		_AddAccumulatedActionsToMSVS(p, spec, actions_to_add)                                                                                                               
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 465, in _AddAccumulatedActionsToMSVS                      
		cmd=command)                                                                                                                                                        
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 435, in _AddCustomBuildToolForMSVS                        
		_ConfigFullName(config_name, c_data), tools=[tool])                                                                                                                 
	  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSProject.py", line 181, in AddFileConfig                                        
		raise ValueError('AddFileConfig: file "%s" not in project.' % path)                                                                                                 
	ValueError: AddFileConfig: file "." not in project.                                                                                                                     
	gyp ERR! configure error                                                                                                                                                
	gyp ERR! stack Error: `gyp` failed with exit code: 1                                                                                                                    
	gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)                                    
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)                                                                                                              
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)                                                                                    
	gyp ERR! System Windows_NT 6.3.9600                                                                                                                                     
	gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                                              
	gyp ERR! cwd E:\zookeeper\zeek\node_modules\node-zookeeper                                                                                                              
	gyp ERR! node -v v0.12.7                                                                                                                                                
	gyp ERR! node-gyp -v v2.0.1                                                                                                                                             
	gyp ERR! not ok                                                                                                                                                         

	npm ERR! Windows_NT 6.3.9600                                                                                                                                            
	npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"                                         
	npm ERR! node v0.12.7                                                                                                                                                   
	npm ERR! npm  v2.11.3                                                                                                                                                   
	npm ERR! code ELIFECYCLE                                                                                                                                                
	npm ERR! zookeeper@3.4.6-7 install: `node-gyp rebuild`                                                                                                                  
	npm ERR! Exit status 1                                                                                                                                                  
	npm ERR!                                                                                                                                                                
	npm ERR! Failed at the zookeeper@3.4.6-7 install script 'node-gyp rebuild'.                                                                                             
	npm ERR! This is most likely a problem with the zookeeper package,                                                                                                      
	npm ERR! not with npm itself.                                                                                                                                           
	npm ERR! Tell the author that this fails on your system:                                                                                                                
	npm ERR!     node-gyp rebuild                                                                                                                                           
	npm ERR! You can get their info via:                                                                                                                                    
	npm ERR!     npm owner ls zookeeper                                                                                                                                     
	npm ERR! There is likely additional logging output above.                                                                                                               
																																											
	npm ERR! Please include the following file with any support request:                                                                                                    
	npm ERR!     E:\zookeeper\zeek\node_modules\node-zookeeper\npm-debug.log                                                                                                

I configured Python 2.6 but still could not make it work.

**Comment by mdlavin** [comment]
Building on windows is not currently supported and is tracked in #78
