### ISSUE TITLE
npm install error on node 0.8.14

### ISSUE THREAD

**Issue by onyas** [yfinkelstein/node-zookeeper#121]
log...

SOLINK_MODULE(target) Release/zookeeper.node: Finished
  ACTION binding_gyp_after_build_target_symlink /usr/local/node-zk-browser/node_modules/zookeeper/build/zookeeper.node
  TOUCH Release/obj.target/after_build.stamp
gyp info ok 
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2:  6549 Segmentation fault: 11  node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
npm info zookeeper@3.4.7-1 Failed to exec install script
npm info /usr/local/node-zk-browser/node_modules/zookeeper unbuild
npm info preuninstall zookeeper@3.4.7-1
npm info uninstall zookeeper@3.4.7-1
npm info postuninstall zookeeper@3.4.7-1
npm ERR! zookeeper@3.4.7-1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 139
npm ERR! 
npm ERR! Failed at the zookeeper@3.4.7-1 install script.
npm ERR! This is most likely a problem with the zookeeper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zookeeper
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-d"
npm ERR! cwd /usr/local/node-zk-browser
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/node-zk-browser/npm-debug.log
npm ERR! not ok code 0

**Comment by onyas** [comment]
npm-debug.log:


12336 info preuninstall zookeeper@3.4.7-1
12337 info uninstall zookeeper@3.4.7-1
12338 verbose true,/usr/local/node-zk-browser/node_modules,/usr/local/node-zk-browser/node_modules unbuild zookeeper@3.4.7-1
12339 info postuninstall zookeeper@3.4.7-1
12340 error zookeeper@3.4.7-1 install: `node-gyp rebuild`
12340 error `sh "-c" "node-gyp rebuild"` failed with 139
12341 error Failed at the zookeeper@3.4.7-1 install script.
12341 error This is most likely a problem with the zookeeper package,
12341 error not with npm itself.
12341 error Tell the author that this fails on your system:
12341 error     node-gyp rebuild
12341 error You can get their info via:
12341 error     npm owner ls zookeeper
12341 error There is likely additional logging output above.
12342 error System Darwin 14.5.0
12343 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-d"
12344 error cwd /usr/local/node-zk-browser
12345 error node -v v0.8.14
12346 error npm -v 1.1.65
12347 error code ELIFECYCLE
12348 verbose exit [ 1, true ]

**Comment by mdlavin** [comment]
Because this says "6549 Segmentation fault: 11 node "dirname "$0"/../../node_modules/node-gyp/bin/node-gyp.js" "$@", I'm inclined to think that it's not a node-zookeeper issue.  I don't have a much time to look into 0.8 support right now, but if you wanted to create a pull request for a fix I could review it.

**Comment by kuebk** [comment]
Seems like it happens because of something in your environment. Just installed node-zookeper using same version of node as you and had no problems. I cannot investigate it further because I don't have Macintosh.

**Comment by mdlavin** [comment]
If you think the issue is Mac specific I can test it.  Hopefully I'll have
time today

**Comment by mdlavin** [comment]
I tested on a Mac today and it installed fine on 0.8.14 for me.  @onyas I would recommend installing node 0.8.14 from nvm.  I'm suspecting your node installation is the issue because of the segmentation fault coming from `node` itself.  I'm going to close for now, but if you can provide more details about how it's related to zookeeper I can look at it again.
