### ISSUE TITLE
how to create a PERSISTENT node?

### ISSUE THREAD

**Issue by Yuliang-Lee** [yfinkelstein/node-zookeeper#122]
how to create a PERSISTENT node?

**Comment by mdlavin** [comment]
I've started a discussion with Yuliang-Lee over email instead of this ticket

**Comment by BigSully** [comment]
Zookeeper has following two constants, but you cannot find constants like ZOO_PERSISTENT or ZOO_EPHEMERAL_SEQUENTIAL:
ZooKeeper.ZOO_SEQUENCE == 1
ZooKeeper.ZOO_EPHEMERAL == 2

However, you can create other two node type with following bitwise operators, as is done by the author in README.md: 
PERSISTENT(0)   == ZooKeeper.ZOO_SEQUENCE & ZooKeeper.ZOO_EPHEMERAL
EPHEMERAL_SEQUENTIAL(3)   == ZooKeeper.ZOO_SEQUENCE | ZooKeeper.ZOO_EPHEMERAL

Or you can directly pass number to the zk.a_create method, ant this will also work: 
PERSISTENT(0)
PERSISTENT_SEQUENTIAL(2)
EPHEMERAL(1)
EPHEMERAL_SEQUENTIAL(3)
