### ISSUE TITLE
Zookeeper 3.4.7 release was retracted

### ISSUE THREAD

**Issue by oleksiyk** [yfinkelstein/node-zookeeper#123]
And is missing on mirrors. See http://mail-archives.apache.org/mod_mbox/zookeeper-user/201602.mbox/%3cD2D52609.39DF5%25cnauroth@hortonworks.com%3e

Posted here just so that everyone knows. I'm happy to prepare a PR as soon as 3.4.8 is out.

**Comment by kuebk** [comment]
The fact 3.4.7 is no longer available on mirrors doesnt affect node-zookeeper. About the bug it was in the server code, the client code is not affected.

**Comment by oleksiyk** [comment]
I mean you can't build it from (fresh) source. Not when you install it from npm.

**Comment by kuebk** [comment]
You can download it from here: http://archive.apache.org/dist/zookeeper/.

**Comment by oleksiyk** [comment]
Oh, cool. thanks!
