### ISSUE TITLE
Unhandled promise rejection TypeError: NativeZk is not a function

### ISSUE THREAD

**Issue by enxebre** [yfinkelstein/node-zookeeper#125]
having "Unhandled promise rejection TypeError: NativeZk is not a function" when:

```
var ZooKeeper = require('zookeeper');
var zookeeperEndopoint = 'zk://192.168.99.100:2181';
var zk = new ZooKeeper({
  connect: zookeeperEndopoint
 ,timeout: 200000
 ,debug_level: ZooKeeper.ZOO_LOG_LEVEL_WARN
 ,host_order_deterministic: false
});
```

**Comment by mdlavin** [comment]
Can you try changing your connection string to be '192.168.99.100:2181' and try again?  Either way, a TypeError should not be thrown, but I'd like to find you a working path

**Comment by kuebk** [comment]
No reply - closing.
