### ISSUE TITLE
Uncouple package version from zookeeper version

### ISSUE THREAD

**Issue by mdlavin** [yfinkelstein/node-zookeeper#130]
So far, package version has been trying to track the zookeeper version. I've kept that up for the last couple of releases because it was always done. For example, when a zookeeper 3.4.8 was released I bumped the version  number to 3.8.1-1 and then a follow up release was 3.4.8-2.

But, there are some issues with that approach. The biggest issue is that npm treats the `-x` version as prerelease and would pick 3.4.7 over 3.4.8-1. Another issue is that it's hard to denote API changes at the node-zookeeper level separately from the zookeeper level. If I wanted to adopt bluebird, I would want to update to a new major version but I can't do that and maintain compatibility with the versioning scheme.

I'd like to propose releasing a 4.0.0 version, based on zookeeper 3.4.9. From that point on, node-zookeeper semantic versioning would include changes to either the node-zookeeper APIs or the zookeeper APIs. The README would be updated to include which version of zookeeper is currently bundled.

**Comment by mdlavin** [comment]
@kuebk and @yfinkelstein the three of us are primary active maintainers so I'd like to get your agreement before I complete the change.

**Comment by kuebk** [comment]
I really like current naming convention but if it no longer suit our needs then it should be changed. :)

**Comment by mdlavin** [comment]
After thinking about it some more, maybe it's best to just stick with the current setup. If I get around to this, I'll do two things.

1.  I'll start publishing builds without the prerelease version so that the latest version gets picked up on normal installs
2. I'll continue to publish with the prerelease version for updates.  So, 3.4.9 adoption would be published as 3.4.9 and 3.4.9-0, -1, -2 (as needed).
