### ISSUE TITLE
npm install fail on node5.11

### ISSUE THREAD

**Issue by jerdbo** [yfinkelstein/node-zookeeper#131]
Downloading zookeeper-3.4.3 from http://apache.mirrors.tds.net/zookeeper/zookeeper-3.4.3/zookeeper-3.4.3.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Unable to build zookeeper library
make: *** [.] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/john/Projects/node-zk-browser/node_modules/zookeeper
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm info lifecycle zookeeper@3.4.6~install: Failed to exec install script

**Comment by mdlavin** [comment]
Can you try to install like this `npm install node-zookeeper@latest`? I'm working on fixing the default version fixed soon.

**Comment by jerdbo** [comment]
thx,it worked
