### ISSUE TITLE
npm install fails on zookeeper error

### ISSUE THREAD

**Issue by davebiagioni** [yfinkelstein/node-zookeeper#135]
Running `npm install` as part of a Docker build, with the following package.json dependencies:

```
  "dependencies": {
    "bluebird": "^3.3.4",
    "body-parser": "^1.15.0",
    "bunyan": "^1.8.1",
    "express": "^4.13.4",
    "graphlib": "^2.1.1",
    "https": "^1.0.0",
    "request": "^2.69.0",
    "request-promise": "^2.0.1",
    "requestretry": "^1.12.0",
    "stream": "0.0.2",
    "xml2js": "^0.4.17",
    "zookeeper": "^3.4.9-3"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "chakram": "^1.4.0",
    "mocha": "^3.0.2",
    "nock": "^8.0.0"
  }
```

results in this error:  (sorry for funky formatting)

```
�[91mnpm�[0m�[91m ERR! Linux 4.9.0-1.el7.elrepo.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
�[0m�[91mnpm ERR! node v6.7.0
npm ERR! npm  v3.10.3
�[0m�[91mnpm ERR!�[0m�[91m code EREADFILE
�[0m�[91m
�[0m�[91mnpm �[0m�[91mERR! Error extracting /root/.npm/zookeeper/3.4.8-2/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/zookeeper/3.4.8-2/package.tgz'
npm ERR! 
npm ERR!�[0m�[91m If you need help, you may report this error at:
�[0m�[91mnpm ERR!     <https://github.com/npm/npm/issues>
�[0m�[91m
�[0m�[91mnpm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
�[0mThe command '/bin/sh -c npm install' returned a non-zero code: 1
```

But bumping the zookeeper version from `3.4.8-2` to `3.4.9-3` resolves the error.  I don't know if this is a zookeeper or npm thing, but thought I would reference it here.

I posted a comment to this issue as well:  https://github.com/npm/npm/issues/15248

**Comment by mdlavin** [comment]
Using node v6.9.2 I created a package.json including the dependencies from above and ran `npm install`. That succeeded without any errors. I changed the node-zookeeper version to be `^3.4.9-3` and it also installed without error.

I also tried putting the package.json version at `3.4.9-2` installing, then bumping to `^3.9.4-2` and reinstalling; that also worked without error.

Given that I can successfully install 3.4.9-2 and 3.4.9-3 without error, and others are seeing the issue with npm and other projects, I'm going to assume it's an edge case in npm's behavior for now. If you find more details from the npm team and think there is something that I can change in the project to avoid the issue, please let me know.

**Comment by davebiagioni** [comment]
Sounds good.  My only comment is that the original version was `3.4.8-2` not `3.4.9-2`, i.e. I went from `3.4.8-2` to `3.4.9-3` to resolve.

Thanks!
