### ISSUE TITLE
The service runs for a long time， the watch_cb of the aw_get_children cannot work

### ISSUE THREAD

**Issue by yqsailor** [yfinkelstein/node-zookeeper#140]
The service runs for a long time， the watch_cb of the aw_get_children cannot work, what should i do?

thanks for first!

**Comment by DavidVujic** [comment]
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. 

I am a new maintainer and would be very happy for feedback and contributions!
