### ISSUE TITLE
aw_get only fires once

### ISSUE THREAD

**Issue by andrew-leonard** [yfinkelstein/node-zookeeper#141]
Here is my code 
```
zk.aw_get('<path>', (type, state, path) => {
   // value has changed 
   console.log('value has changed');
}, (rc, error, stat, data) => {
    console.log('initial data');
});
```

When I use zookeeper cli to update the value of config at <path>, the console log for "value has changed" is only fired on the first change of the value. Any subsequent changes are not causing the console.log to fire.

Any thoughts on this? Am I using the API wrong?

**Comment by DavidVujic** [comment]
Hi @andrew-leonard! Is this issue still relevant, or have you found a solution?

I am a new maintainer and would be very happy for feedback and contributions!

**Comment by toBeTheLight** [comment]
@andrew-leonard You are right, watcher will only be fired once, you have to bind a new watcher.

[Conditional updates and watches](https://zookeeper.apache.org/doc/current/zookeeperOver.html)
> ZooKeeper supports the concept of watches. Clients can set a watch on a znode. A watch will be triggered and removed when the znode changes.
