### ISSUE TITLE
Refactor deprecated JavaScript gettter/setter feature

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#149]
`lib/zookeeper.js` use deprecated features for creating property getters and setters. It should be replaced with ECMAScript 201x compliant code.

The deprecated features are `__defineGetter__` and `__defineSetter__`.

```JavaScript
  function proxyProperty(name) {
    self.__defineGetter__(name, function(){
      return self._native[name];
    });
    self.__defineSetter__(name, function(val){
      self._native[name] = val;
    });
  }
```

**Comment by jbienkowski311** [comment]
Please check my pull request - it should solve this issue :wink:
On the other hand - what versions of Node do we support? Maybe we could move to ES6 class instead of function/prototype approach?

**Comment by DavidVujic** [comment]
Great, I'll have a look!

The versions of Node supported are 8 and 10 (the two latest LTS versions) - and soon also version 12. ES6 classes should work fine. Maybe this PR is good enough for now, a rewrite to ES6 can be in a different PR?

**Comment by jbienkowski311** [comment]
I think that is a good approach. The change to ES6 will be much much more work and this provides an easy and quick fix to the current code base.
