### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#161]
Add an Issues template. https://github.com/yfinkelstein/node-zookeeper/community

**Comment by luc-boussant** [comment]
I add a PR with a new issues template : https://github.com/yfinkelstein/node-zookeeper/pull/164

**Comment by luc-boussant** [comment]
@DavidVujic  Tell if this is good for you

**Comment by DavidVujic** [comment]
I've added some feedback in the pull request!
