### ISSUE TITLE
build script: fails when the path contain spaces

### ISSUE THREAD

**Issue by davidvujic-svenskaspel** [yfinkelstein/node-zookeeper#165]
Example:
`/Users/david/My Company/myapp/node_modules/zookeeper/deps/zookeeper`

Gives an error:
```bash
/bin/sh: /Users/david/My: No such file or directory
```

**Comment by davidvujic-svenskaspel** [comment]
Workaround: 
```CFLAGS=-Wno-error=format-overflow npm install```

**Comment by jbienkowski311** [comment]
Looks like `return process.cwd().replace(' ', '\\ ');` in `scripts/env.js` should do the trick :wink:

**Comment by jbienkowski311** [comment]
What looked like an easy task took me much more time than I would like to admit... However this issue cannot be fixed. `node-gyp` itself does not support directories with spaces, see [nodejs/node-gyp#65](https://github.com/nodejs/node-gyp/issues/65), [@tensorflow/tfjs#711](https://github.com/tensorflow/tfjs/issues/711).

```
File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 970, in WriteActions
    "Spaces in action output filenames not supported (%s)"  % output)
AssertionError: Spaces in action output filenames not supported (/home/bienko/dev/projects with space/node-zookeeper/build/zookeeper.node)
```

**Comment by DavidVujic** [comment]
@jbienkowski311 Thank you very much for taking time and finding the root cause of the issue!
