### ISSUE TITLE
Can not install 4.x using npm 

### ISSUE THREAD

**Issue by usea** [yfinkelstein/node-zookeeper#169]
```
➜  zookeeper-test npm i zookeeper

> zookeeper@4.0.3 install /Users/youhaiyang/Documents/project/test/zookeeper-test/node_modules/zookeeper
> node ./scripts/prepublish.js && npm run build

cd /Users/youhaiyang/Documents/project/test/zookeeper-test/node_modules/zookeeper/deps
```
stucked here and no response 

**Desktop:**
 - OS: Mac OS Mojave
 - Node.js version: 8.x/10.x/12.x

**Comment by DavidVujic** [comment]
@usea  It looks like the installer is stuck when trying to download the ZooKeeper source code from http://archive.apache.org/dist/zookeeper/  - are you behind a company proxy when installing?

**Comment by usea** [comment]
> @usea It looks like the installer is stuck when trying to download the ZooKeeper source code from http://archive.apache.org/dist/zookeeper/ - are you behind a company proxy when installing?

Thanks, it is indeed a problem with my company's network. But this network problem can't be solved temporarily, is there any way to get this zookeeper file from a local cache folder?(I can download it manually)

**Comment by DavidVujic** [comment]
The package is dependent on the Apache source code. If you are able to download the zookeeper-3.4.13.tar.gz file from the Apache url manually somehow, you could solve it with a (sort of ugly) workaround:

1. Clone this repo
2. Copy the tar.gz file into the deps/ folder of the repo
3. Run npm install
4. In your app: create a subfolder in your node_modules folder: node_modules/zookeeper
5. copy the entire cloned repo with the built client into the node_modules/zookeeper of your app.

**Comment by usea** [comment]
> The package is dependent on the Apache source code. If you are able to download the zookeeper-3.4.13.tar.gz file from the Apache url manually somehow, you could solve it with a (sort of ugly) workaround: 1. Clone this repo 2. Copy the tar.gz file into the deps/ folder of the repo 3. Run npm install 4. In your app: create a subfolder in your node_modules folder: node_modules/zookeeper 5. copy the entire cloned repo with the built client into the node_modules/zookeeper of your app.

@DavidVujic OK, thanks
