### ISSUE TITLE
Windows (CMake): less verbose output when compiling

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#182]
**Is your feature request related to a problem? Please describe.**
The output is too verbose when running `npm install` to start the build process. Especially the output from the `./configure` command creates a lot of log rows in the console.

**Describe the solution you'd like**
Add these flags to the `./configure` command (in the `scripts/build.js` file):
```bash
--enable-silent-rules --quiet
```
This will shorten the output on Mac OS and Linux machines. On Windows there should be possible to shorten the CMake output too, a feature to investigate!

**Comment by jbienkowski311** [comment]
For `configure` script we definitely need `--enable-silent-rules --quiet` flags. For `make` command we could use either `make > /dev/null` or `--no-print-directory --quiet` flags. I will boot into Windows and investigate CMake flags.
Providing additional flag to `npm install` could reveal suppressed output - it would be very useful during the development process. For example something like `ZK_BUILD_VERBOSE=1 npm install`.

**Comment by jbienkowski311** [comment]
I have experimented with build on Windows, but with no great success. I did not find any useful CMake flags, but to be completely honest I do not think we need to worry about it. `node_zookeeper` supports Windows only for development, and as I stated before, for development we should leave the build output "as is". 
If someone wants to debug it further, I will be more than glad to help.

**Comment by DavidVujic** [comment]
I'll leave this issue open, for further investigation if there is possible to do something with the verbos output in Windows.

**Comment by DavidVujic** [comment]
Maybe these links can be of any help during investigation:
https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_MESSAGE.html
https://cmake.org/cmake/help/latest/command/ctest_configure.html
