### ISSUE TITLE
ESLint: the scripts folder

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#184]
**Is your feature request related to a problem? Please describe.**
The JavaScript files in the `scripts` folder should not be excluded from ESLint.

**Describe the solution you'd like**
Remove the `scripts` path from the `.eslintignore` file.

This will most likely cause issues to be solved in one or more of the files in the `scripts` folder.

**Comment by jbienkowski311** [comment]
Why do we exclude `lib` directory? The whole purpose of eslint is to keep the codebase consistent with defined rules. Maybe we should start from defining eslint rules properly?

**Comment by DavidVujic** [comment]
Let’s exclude the lib folder until converting it to ES201x! This repo use lint rules from AirBnb (very strict) and having the entire JavaScript codebase checked is in the roadmap. My hopes are before the end of this year. :)
