### ISSUE TITLE
ZooKeeper 3.5.5: new node types

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#210]
Is `New node types: Container, TTL` a feature that should be implemented in this client?

http://zookeeper.apache.org/releases.html#releasenotes

**Comment by dreusel** [comment]
It would make me very happy :)

**Comment by DavidVujic** [comment]
Great! Will prioritize this one.

**Comment by DavidVujic** [comment]
Added in https://github.com/yfinkelstein/node-zookeeper/pull/265
