### ISSUE TITLE
Handling ZNOTHING inside may not be a good idea.

### ISSUE THREAD

**Issue by toBeTheLight** [yfinkelstein/node-zookeeper#228]
**Is your feature request related to a problem? Please describe.**
After our server has started up, zookeeper_process would returned no response more than 10 times sometime. In this case, the connection and data fetch are all still working. But connection will be closed by 10 times ZNOTHING, causing another infinite loop.

**Describe the solution you'd like**
Emit a event like empty_response to make user able to handle it ranther than hande it inside.

**Additional context**
Although we have not found why it had happened so many times (may be related to network conditions), but after reading the zookeeper repository we think that ZNOTHING is [an expected response](https://github.com/apache/zookeeper/blob/176bd68222f3a3bddac9deb412eee7f538cb01ca/zookeeper-client/zookeeper-client-c/tests/TestWatchers.cc#L326), not an error.

**Comment by DavidVujic** [comment]
A workaround is to exit the Node.js process and restart. I'll  try to implement a solution like you propose, thank you for reporting!

**Comment by toBeTheLight** [comment]
@DavidVujic 
I have made a repository to observe the factors that affect the empty response.
You can run it with readme, may be helpful.
[Here](https://github.com/toBeTheLight/node-zookeeper) it is.

**Comment by toBeTheLight** [comment]
I have made anther test which gets a node of large data size.

**Comment by toBeTheLight** [comment]
Could i make a PR for this with Empty event when there are many empty responses？

**Comment by DavidVujic** [comment]
Do it! :)

/David
