### ISSUE TITLE
Count limits of "empty response" to close client.

### ISSUE THREAD

**Issue by toBeTheLight** [yfinkelstein/node-zookeeper#233]
**Describe the bug**
When getting a large node or getting a long children list, It is easy to reach 10 "empty responses"

**To Reproduce**
[BUG reproduce](https://github.com/toBeTheLight/node-zookeeper-issue) 
As ISSUE 228-2 in README.md

1. Run `npm i`
2. Start a zookeeper server
2. cd issue228-2
3. Change the address in options.js to the server address
3. Run `node init-data.js` until enough nodes have been appended to root node (create 100000 nodes to root node) and the data size of root node have reached the upper limit.
4. Run `node get-node.js` (get data of root node) for serveral times. Observe the log of`yield:zookeeper_process returned no response too many times`
5. Run `node get-children.js` (get children of root node) for serveral times. Observe the log of`yield:zookeeper_process returned no response too many times`

after I run the example, the largest number I had saw is 82.

**Expected behavior**
Maybe 300 (larger than 3 * 82) is a safe limit count for empty response.

**Comment by jbienkowski311** [comment]
Is fixed by #278

**Comment by DavidVujic** [comment]
@toBeTheLight Thanks to the pull request #278 this might be solved now. :smile: 

Thank you @jbienkowski311 for connecting the PR and this issue. :clap: 

I'll close this one. If you still experience issues, please reopen or create a new issue.
