### ISSUE TITLE
install error: /tmp/build/src/node_modules/zookeeper: Command failed.

### ISSUE THREAD

**Issue by hwzhangd** [yfinkelstein/node-zookeeper#234]
**Describe the bug**
on linux, when use yarn, it will push error 

i got, i because liunx is too old, only have sha1sum rather than shasum, can u make it compatible?

**Desktop (please complete the following information):**
 - OS: x86_64-redhat-linux 
 - Node.js version:  v10.16.2
 - C/C++ compiler and version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-23)

**Comment by jbienkowski311** [comment]
Hi @hwzhangd! Do you have sha512sum command available? Unfortunately sha1sum uses different hashing algorithm, therefore it won't work. If you have sha512sum command available, I could make a fix. 

Regards

**Comment by hwzhangd** [comment]
yes,  i have. i will be very thanks if you fixed it

**Comment by DavidVujic** [comment]
I have published a new version to npm. Thank you @hwzhangd and @jbienkowski311!
