### ISSUE TITLE
How can I use node-zookeeper offline?

### ISSUE THREAD

**Issue by michaelyefet** [yfinkelstein/node-zookeeper#248]
I've been trying to install zookeeper module offline (behind corporate walls). Usually, I use [this script](https://www.npmjs.com/package/npm-package-downloader) to download modules, and then publish it (and all it's dependencies) to verdaccio in my closed network - and it works. With zookeeper, it uploads it to verdaccio successfully but when I try to add it to my project using

`yarn add zookeeper --update-checksums`
I get an error when an automatic node-gyp rebuild is triggered -

```
gyp http GET https://nodejs.org/download/release/v12.16.3/node-v12.16.3- 
headers.tar.gz
gyp WARN install got an error, rolling back install
```
After reading the [following issue](https://github.com/nodejs/node-gyp/issues/812) I've downloaded the missing headers, entered it to my closed network and then used

`yarn config set nodedir SOME_LOCAL_FOLDER`
I placed node-v12.16.3-headers.tar.gz in SOME_LOCAL_FOLDER and then tried to run yarn add again. Then, I got an error saying I don't have visual studio installed, like in [here](https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c). I installed visual studio 2015 and the error went away. But now, I'm getting a new error saying

```
SOME_LOCAL_FOLDER/common.gypi not found (cwd: DEVELOPING_FOLDER\node_modules\zookeeper) while reading 
includes of binding.gyp wile trying to load 
binding.gyp.
```
I feel like I'm going in circles. Can anyone help?

> node version - 12.16.3 
> yarn version - 1.7.0

**Comment by DavidVujic** [comment]
Hi @michaelyefet, thank you for reaching out about the issues with installing the package. 

I'm not sure why you cannot install it, we run builds on Travis CI on Windows without issues. Here's[ the log from the latest run](https://travis-ci.com/github/DavidVujic/node-zookeeper/jobs/423312924), maybe you will get some ideas from it.

Could it be the `node-gyp` version that causes it? Perhaps a long shot, but here are instructions for Windows users on how to install it with the Python dependencies: https://github.com/nodejs/node-gyp#installation

Let me know how it goes and if I can assist you in any way!

**Comment by DavidVujic** [comment]
I'm closing this one. Please reopen it if this still is a problem!
