### ISSUE TITLE
Unexected behavior: a_exists throws/rejects when node does not exist

### ISSUE THREAD

**Issue by dreusel** [yfinkelstein/node-zookeeper#254]
I would expect it to simply return null, since there is nothing 'exceptional' about a node not existing in such a case. Treating it this way leads to cases where lots of code will end up in catch blocks.

If this is the intended behavior then a note in the documentation might be appropriate.

**Comment by DavidVujic** [comment]
Thank you for reporting this!

**Comment by DavidVujic** [comment]
I think this behavior of the client need some investigation. Why does the client raise an exception? Maybe it is correct? The exception contain the message `101 no node`.
