### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=node abi=83 uv=1 libc=glibc 

### ISSUE THREAD

**Issue by andrew-lazarev-deepsee** [yfinkelstein/node-zookeeper#268]
Hi guys, I got a runtime error after deploying code to AWS lambda,
I'm using nodejs14 but the same result occurs with earlier versions of node.

Please check the attached error message:

`{
  "errorType": "Error",
  "errorMessage": "No native build was found for platform=linux arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.15.4\n    loaded from: /var/task/node_modules/zookeeper\n",
  "trace": [
    "Error: No native build was found for platform=linux arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.15.4",
    "    loaded from: /var/task/node_modules/zookeeper",
    "",
    "    at Function.load.path (/var/task/node_modules/node-gyp-build/index.js:59:9)",
    "    at load (/var/task/node_modules/node-gyp-build/index.js:21:30)",
    "    at Object.<anonymous> (/var/task/node_modules/zookeeper/lib/zookeeper.js:8:43)",
    "    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
    "    at Module.load (internal/modules/cjs/loader.js:928:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
    "    at Module.require (internal/modules/cjs/loader.js:952:19)",
    "    at require (internal/modules/cjs/helpers.js:88:18)",
    "    at Object.<anonymous> (/var/task/node_modules/zookeeper/lib/zk_promise.js:4:19)"
  ]
}`

**Comment by DavidVujic** [comment]
Thank you for reporting this @andrew-lazarev-deepsee!

I'll have a look. At first look it reminds me of a different code project that had issues in Linux Arch, because of differences in how OS libraries are linked. It is only a guess, based on what I can see here. I will investigate further.

**Comment by andrew-lazarev-deepsee** [comment]
Hey, @DavidVujic thanks for your attention for this issue! 
Meanwhile, my team found some workaround and that solution doesn't require the usage of ZK server.
So feel free to close this Issue!

**Comment by DavidVujic** [comment]
Good to hear that you have found a solution!
