### ISSUE TITLE
Unit tests: replace tape with Ava

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#276]
**Describe the bug**
This is an issue only when installing the source code (not the release built `npm package`) and is about the `devDependencies`.

The library `tap-spec` seems to have an outdated sub dependency that is raising warnings on install.

`tap-spec` is used in this repo to print out unit tests in a nice way.

**To Reproduce**
1. Clone this repo.
2. run `npm install`

**Error Log**
```bash
# npm audit report

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://npmjs.com/advisories/1700
fix available via `npm audit fix --force`
Will install tap-spec@2.2.2, which is a breaking change
node_modules/trim
  tap-out  *
  Depends on vulnerable versions of trim
  node_modules/tap-out
    tap-spec  2.1.2 || >=3.0.0
    Depends on vulnerable versions of tap-out
    node_modules/tap-spec
```

**Expected behavior**
`npm install` should not raise any `audit` warnings.

**Comment by jbienkowski311** [comment]
I think we should move to the forked lib called [tap-in](https://github.com/spencermountain/tap-in) as tap-out seems to not be maintained by its author anymore.
It  would also close this issue.

**Comment by DavidVujic** [comment]
Good idea @jbienkowski311!

**Comment by DavidVujic** [comment]
I'm leaning towards switching out `tape` to `ava`. https://github.com/avajs/ava
