### ISSUE TITLE
Add prebuilds for node 18

### ISSUE THREAD

**Issue by miroslavpokorny** [yfinkelstein/node-zookeeper#323]
There was released new major LTS version (18.x.x) of node.js on 25th October 2022.

It will be great to add zookeeper prebuilds for this version.

**Comment by DavidVujic** [comment]
Good idea @miroslavpokorny! I will add Node.js 17 prebuilds as soon as possible.

**Comment by DavidVujic** [comment]
A new version of this package is released to npm! The latest version contains Node.js v.18 prebuilds for Mac OS X (intel and M1), plus Windows.
