### ISSUE TITLE
What is the use of watcher<boolean> in the APIs?

### ISSUE THREAD

**Issue by 24x7soumya** [yfinkelstein/node-zookeeper#326]

**Comment by DavidVujic** [comment]
Hi @24x7soumya!

When set to `true`, there should be a watcher added and events are sent to the client. There's corresponding functions where you can pass explicit callback functions. I don't remember if I've ever used a `true` value when using the one with booleans, though.

I think this is the place where it is done from the C wrapper: https://github.com/yfinkelstein/node-zookeeper/blob/master/src/node-zk.cpp#L481

And re-emitted in the JavaScript client: https://github.com/yfinkelstein/node-zookeeper/blob/master/lib/zookeeper.js#L79

**Comment by 24x7soumya** [comment]
Thanks for the response @DavidVujic . It is a bit confusing about how the event will be received.
But I got the idea.
