### ISSUE TITLE
Error: dlopen(/private/tmp/node_modules/zookeeper/build/Release/zookeeper.node, 0x0001): symbol not found in flat namespace '_sasl_client_new

### ISSUE THREAD

**Issue by rambo-panda** [yfinkelstein/node-zookeeper#332]
**Describe the bug**
symbol not found in flat namespace '_sasl_client_new

**Screenshots**
![image](https://github.com/yfinkelstein/node-zookeeper/assets/2776050/fe2ef452-624f-4c5e-b07f-5186cdbec525)

**Desktop (please complete the following information):**
 - OS: macos 12.0.1 (21A559)
 - Node.js version:  20.10.0
 - C/C++ compiler and version: 
 Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by DavidVujic** [comment]
Thank you for reporting @rambo-panda!

I will have a look at this. Another thing that is currently missing is a pre-build for Node.js v20. I will add that shortly.

**Comment by DavidVujic** [comment]
Meanwhile, could you give Node.js 18 a try, otherwise with the same setup?

**Comment by DavidVujic** [comment]
I couldn't reproduce this error, but suspect it has something to do with a missing C dependency and when building the Node.js AddOn. I have updated zookeeper to v6.1.0 that includes prebuilds for Mac OS X and Node.js v20. This should solve your issues. 

Please reopen if this doesn't solve it. Thank you again for reporting 🙏
