### ISSUE TITLE
How can I listen to the connection state changes events?

### ISSUE THREAD

**Issue by fstonezst** [yfinkelstein/node-zookeeper#351]
Users of the LeaderSelector must pay attention to any connection state changes. If an instance becomes the leader, it should respond to notification of being SUSPENDED or LOST. If the SUSPENDED state is reported, the instance must assume that it might no longer be the leader until it receives a RECONNECTED state. If the LOST state is reported, the instance is no longer the leader and its leader task should exit.

**Comment by DavidVujic** [comment]
If I understand your question correctly, it sounds like the concept of __leader election__. This is supported by the ZooKeeper client. The ZooKeeper server is an event driven system, and clients can register listeners.

There's some examples of this thing in the [examples folder](https://github.com/yfinkelstein/node-zookeeper/blob/master/examples/index.js#L41). It was quite some time ago I wrote this, but I tried to do something in the style of the contents in [this ZooKeeper book](https://www.oreilly.com/library/view/zookeeper/9781449361297/).

**Comment by fstonezst** [comment]
> If I understand your question correctly, it sounds like the concept of **leader election**. This is supported by the ZooKeeper client. The ZooKeeper server is an event driven system, and clients can register listeners.
> 
> There's some examples of this thing in the [examples folder](https://github.com/yfinkelstein/node-zookeeper/blob/master/examples/index.js#L41). It was quite some time ago I wrote this, but I tried to do something in the style of the contents in [this ZooKeeper book](https://www.oreilly.com/library/view/zookeeper/9781449361297/).

Thank you for your response! Actually, I was just looking to understand how to use this SDK to listen for changes in the client’s connection status with ZooKeeper. Specifically, I want to know how to detect when a client disconnects from the server and when the session becomes invalid. Any guidance on this would be appreciated!

**Comment by DavidVujic** [comment]
Here's examples on the events fired for the connection status of a client:
https://github.com/yfinkelstein/node-zookeeper/blob/master/examples/wrapper.js#L36

In the example, there's also a suggestion on how to handle disconnects (the `connecting` event) with retries.

**Comment by DavidVujic** [comment]
You can try the client out by running a local ZooKeeper (I would recommend running it in docker). 

Running ZooKeeper server: 
```shell
docker run --rm -p 2181:2181 zookeeper
```

Running your Node.js client, in a separate terminal:
```shell
# here I am using the existing examples: creating nodes, electing a leader and such.
node examples/index.js
```

Test the connection, by starting/stopping the server:
```shell
docker restart <the-container-id-here>
```
And monitor how the client behaves. It is the `connect`, `connecting` and `close` events.

Recording:
![zookeeper-connection-test](https://github.com/user-attachments/assets/814188f7-3e36-4ea9-a8ba-d1720c6ebfdd)

**Comment by fstonezst** [comment]
> You can try the client out by running a local ZooKeeper (I would recommend running it in docker).
> 
> Running ZooKeeper server:
> 
> ```shell
> docker run --rm -p 2181:2181 zookeeper
> ```
> 
> Running your Node.js client, in a separate terminal:
> 
> ```shell
> # here I am using the existing examples: creating nodes, electing a leader and such.
> node examples/index.js
> ```
> 
> Test the connection, by starting/stopping the server:
> 
> ```shell
> docker restart <the-container-id-here>
> ```
> 
> And monitor how the client behaves. It is the `connect`, `connecting` and `close` events.
> 
> Recording: ![zookeeper-connection-test](https://private-user-images.githubusercontent.com/301286/359466420-814188f7-3e36-4ea9-a8ba-d1720c6ebfdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjIwMjAsIm5iZiI6MTcyNDE2MTcyMCwicGF0aCI6Ii8zMDEyODYvMzU5NDY2NDIwLTgxNDE4OGY3LTNlMzYtNGVhOS1hOGJhLWQxNzIwYzZlYmZkZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMzQ4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTcxZTAyY2I3MGY4NTE0NzVjMGQ1OWE5ZTkzOWRkMWRjZWQ5N2ExMWI2YTUzNWMxM2FiMTVjMTZiZGE4MzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ma7ggb5_YzilYwTNbMbhHOW4hZU6iCdlHJrQHTdDVgY) [ ![zookeeper-connection-test](https://private-user-images.githubusercontent.com/301286/359466420-814188f7-3e36-4ea9-a8ba-d1720c6ebfdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjIwMjAsIm5iZiI6MTcyNDE2MTcyMCwicGF0aCI6Ii8zMDEyODYvMzU5NDY2NDIwLTgxNDE4OGY3LTNlMzYtNGVhOS1hOGJhLWQxNzIwYzZlYmZkZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMzQ4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTcxZTAyY2I3MGY4NTE0NzVjMGQ1OWE5ZTkzOWRkMWRjZWQ5N2ExMWI2YTUzNWMxM2FiMTVjMTZiZGE4MzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ma7ggb5_YzilYwTNbMbhHOW4hZU6iCdlHJrQHTdDVgY) ](https://private-user-images.githubusercontent.com/301286/359466420-814188f7-3e36-4ea9-a8ba-d1720c6ebfdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjIwMjAsIm5iZiI6MTcyNDE2MTcyMCwicGF0aCI6Ii8zMDEyODYvMzU5NDY2NDIwLTgxNDE4OGY3LTNlMzYtNGVhOS1hOGJhLWQxNzIwYzZlYmZkZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMzQ4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTcxZTAyY2I3MGY4NTE0NzVjMGQ1OWE5ZTkzOWRkMWRjZWQ5N2ExMWI2YTUzNWMxM2FiMTVjMTZiZGE4MzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ma7ggb5_YzilYwTNbMbhHOW4hZU6iCdlHJrQHTdDVgY) [ ](https://private-user-images.githubusercontent.com/301286/359466420-814188f7-3e36-4ea9-a8ba-d1720c6ebfdd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjIwMjAsIm5iZiI6MTcyNDE2MTcyMCwicGF0aCI6Ii8zMDEyODYvMzU5NDY2NDIwLTgxNDE4OGY3LTNlMzYtNGVhOS1hOGJhLWQxNzIwYzZlYmZkZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMzQ4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTcxZTAyY2I3MGY4NTE0NzVjMGQ1OWE5ZTkzOWRkMWRjZWQ5N2ExMWI2YTUzNWMxM2FiMTVjMTZiZGE4MzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ma7ggb5_YzilYwTNbMbhHOW4hZU6iCdlHJrQHTdDVgY)

Thank you very much for providing the detailed testing process. I simulated a client disconnect by simply disconnecting my computer from the network. However, I noticed that no events were triggered when the network was disconnected.

Is there a way to listen for events specifically when the network disconnects?

Thanks again for your support!

**Comment by DavidVujic** [comment]
I think the `connecting` event should be triggered actually. Were you running a client towards a ZooKeeper Server in a network (not locally)?

**Comment by fstonezst** [comment]
> I think the `connecting` event should be triggered actually. Were you running a client towards a ZooKeeper Server in a network (not locally)?

Yes, I was connecting to a remote ZooKeeper server. In fact, when I lost the network connection, the connecting event did not get triggered. I think you could replicate this phenomenon by stopping your ZooKeeper service.

**Comment by DavidVujic** [comment]
Interesting! In the recording, the very last thing done is stopping the ZooKeeper server process and the client ends up in a `connecting` state until giving up (the example code exits the Node.js process).

How do you connect, are you using the example code? Would you mind share how you do?

**Comment by fstonezst** [comment]
> Interesting! In the recording, the very last thing done is stopping the ZooKeeper server process and the client ends up in a `connecting` state until giving up (the example code exits the Node.js process).
> 
> How do you connect, are you using the example code? Would you mind share how you do?


OK， This is my operational video

https://github.com/user-attachments/assets/9b1a5800-ce35-43d4-a88a-eced9410281f

**Comment by DavidVujic** [comment]
@fstonezst I got a notification about a new message from you, but it seems to have been removed?

**Comment by fstonezst** [comment]
> Interesting! In the recording, the very last thing done is stopping the ZooKeeper server process and the client ends up in a `connecting` state until giving up (the example code exits the Node.js process).
> 
> How do you connect, are you using the example code? Would you mind share how you do?

OK，here’s a summary of my operation process, which I’ve captured in a GIF below:
![mnggiflab-compressed-mnggiflab-compressed-mnggiflab-from-video-to-gif-2024_08_21_09_54_13](https://github.com/user-attachments/assets/fec60e56-4d52-42eb-bf12-37c00da1ba58)

**Comment by DavidVujic** [comment]
Thank you for sharing!

It looks like the Node process exists after a period of being offline from the network ("operation timeout"). I think this is because of a network error, and not a connection error to the server. I _think_ this make sense, because this would indicate that something is wrong with the network access of the running process (and the process would exit).

It is possible to set the `timeout` (ms), and I think this will make the client stay alive for a longer period of time and wait until the timeout expires.

**Comment by fstonezst** [comment]
> Thank you for sharing!
> 
> It looks like the Node process exists after a period of being offline from the network ("operation timeout"). I think this is because of a network error, and not a connection error to the server. I _think_ this make sense, because this would indicate that something is wrong with the network access of the running process (and the process would exit).
> 
> It is possible to set the `timeout` (ms) in the values to the constructor, and I think this will make the client stay alive for a longer period of time and wait until the timeout expires.

Thank you for your response! If the connection event doesn’t get triggered in this situation, are there other ways to detect when the client disconnects from the server?

**Comment by DavidVujic** [comment]
It's a bit difficult to see, but when I look at your recording again it looks like that you stopped the process, right? Looks like a "session connecting" just before.

It is the ZooKeeper server, not the client, that elects leader. If your client is offline, with no access to the Internet, I don't think there is much the client can do. Or do I misunderstand you?

**Comment by DavidVujic** [comment]
If you have more than one client connected, if the leader is disconnected the other client would be the leader. This is directed by the ZooKeeper server. Can you give that a try?

**Comment by DavidVujic** [comment]
The nodes you register can be of type `ephemeral`, that would mean if disconnected they would be removed (and lose the leader position).

**Comment by fstonezst** [comment]
> If you have more than one client connected, if the leader is disconnected the other registered worker would be the leader. This is directed by the ZooKeeper server. Can you give that a try?

That's certainly true. However, the issue arises when the leader client loses its connection with the server. If the leader does not receive any events indicating a disconnection, it may not realize that it has lost its role as the leader. In this case, the other followers in the cluster will initiate an election to choose a new leader. As a result, there could be a situation where two leaders exist in the cluster simultaneously. I hope this clarifies the situation for you.

**Comment by DavidVujic** [comment]
I think the `ephemeral` feature of the ZooKeeper server would help you out here. Otherwise, how would you expect an offline client to un-register a leader if it doesn't have internet connection?

**Comment by fstonezst** [comment]
> I think the `ephemeral` feature of the ZooKeeper server would help you out here. Otherwise, how would you expect an offline client to un-register a leader if it doesn't have internet connection?

Thank you for your suggestion! I am already using ephemeral znodes. I hope the summary on error handling from the wiki that I provided can help clarify my issue. I really appreciate your support!

Here’s the link: [Error Handling](https://curator.apache.org/docs/recipes-leader-election/)

**Comment by DavidVujic** [comment]
Here's another recording: the ZooKeeper Server is the bigger terminal window to the left. To the right, I start two clients, both trying to register a leader. 

One of them is the leader, and when I kill that process the ZooKeeper Server reacts to it and sets a new leader. There should not be possible to have two leaders as I understand ZooKeeper.

![leader-election](https://github.com/user-attachments/assets/b84cb1a2-b142-4cd5-b4d8-98bad17f10e3)
