### ISSUE TITLE
'close' event not emitted, even though zk.state goes from connected to 0

### ISSUE THREAD

**Issue by emiloslavsky** [yfinkelstein/node-zookeeper#71]
Hi!  I'm connecting to zookeeper successfully and registering 'close' handler:
<code>zk = new ZK(zkOptions);
zk.on('close', closeHandle);
</code>

Things work well for about a day, then connection to zookeeper breaks and I see
<code>2012-09-14 01:51:37,599:17550:ZOO_ERROR@handle_socket_error_msg@1603: Socket [10.191.37.59:2181] zk retcode=-4, errno=112(Host is down): failed while receiving a server response
2012-09-14 01:51:37,599:17550:ZOO_ERROR@zk_io_cb@246: yield:zookeeper_process returned error: -4 - connection loss</code>

At this point zk.state is 0, yet my closeHandle is never invoked.

**Comment by jamc** [comment]
Long time, but i resolve it like @kuebk said, using the connecting event:

```javascript
zkClient.once('connecting', function(err) {
  // Do something here
});
```

**Comment by kuebk** [comment]
Closing.
