### ISSUE TITLE
Support for Windows OS

### ISSUE THREAD

**Issue by tomgutz** [yfinkelstein/node-zookeeper#78]
From what I experience and what info I gathered from the author, Windows OS is not supported by this tool. Do you guys have a specific timeline that this will be implemented? This is very important since on our project we have to support at a minimum MacOS and WinOS for our developers. Thanks.

**Comment by caomu** [comment]
Same... eagerly
+1

**Comment by candyleer** [comment]
+1

**Comment by ndxbn** [comment]
Any update?

**Comment by mdlavin** [comment]
I don't have any plans to implement Windows support, but I'd be willing to review and merge if somebody wants to contribute support

**Comment by DavidVujic** [comment]
Here's a fork with ongoing work to enable windows support. Currently there are issues with sockets that disconnects, that I have some trouble solving though. Would be very happy to get some help with it! https://github.com/DavidVujic/node-zookeeper/tree/windows_support
