### ISSUE TITLE
Unable to build on Solaris?

### ISSUE THREAD

**Issue by ghost** [yfinkelstein/node-zookeeper#84]
> zookeeper@3.4.6 install /opt/recent-images/node_modules/node-micro-service/node_modules/zookeeper
> node-gyp rebuild

make: Entering directory `/opt/recent-images/node_modules/node-micro-service/node_modules/zookeeper/build'
  ACTION binding_gyp_libzk_target_build_zk_client_lib .
  TOUCH Release/obj.target/libzk.stamp
  CXX(target) Release/obj.target/zookeeper/src/node-zk.o
../src/node-zk.cpp:13:23: fatal error: zookeeper.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/zookeeper/src/node-zk.o] Error 1
make: Leaving directory`/opt/recent-images/node_modules/node-micro-service/node_modules/zookeeper/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/recent-images/node_modules/node-micro-service/node_modules/zookeeper
gyp ERR! node -v v0.8.18
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok
npm ERR! zookeeper@3.4.6 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the zookeeper@3.4.6 install script.
npm ERR! This is most likely a problem with the zookeeper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zookeeper
npm ERR! There is likely additional logging output above.

npm ERR! System SunOS 5.11
npm ERR! command "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! cwd /opt/recent-images
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/recent-images/npm-debug.log
npm ERR! not ok code 0

**Comment by DavidVujic** [comment]
I'm closing this one. Please create a new issue (and PR if possible) if you think it is a mistake and Solaris support is still relevant! Thank you for contributing with this error report. I am a new maintainer and would be very happy for feedback and contributions!
