### ISSUE TITLE
Support for recursive delete (rmr)

### ISSUE THREAD

**Issue by devoncrouse** [yfinkelstein/node-zookeeper#92]
Added in 3.4.0; note, in 3.5+ it will change from 'rmr' to 'deleteall':
https://issues.apache.org/jira/browse/ZOOKEEPER-729

**Comment by DavidVujic** [comment]
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!
