### ISSUE TITLE
Supporting multi() - Multiple atomic operations

### ISSUE THREAD

**Issue by tcz** [yfinkelstein/node-zookeeper#94]
It would be lovely to get support for `multi()`, for some locking scenarios it's essential.

http://zookeeper.apache.org/doc/r3.4.3/api/org/apache/zookeeper/ZooKeeper.html#multi%28java.lang.Iterable%29

**Comment by DavidVujic** [comment]
Maybe this feature could be implemented in pure JavaScript, by using Promises and the `Promise.all` feature?

I think something similar is possible with the current version, by adding a wrapper around the zookeeper JavaScript code.

I will close this one, please open a new Issue if you think it's a mistake!
